"""add content_hash to feedbacks

Revision ID: 3b7ddcabf1ce
Revises: 68a3c7b85df0
Create Date: 2026-07-01 14:41:29.204976

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3b7ddcabf1ce'
down_revision: Union[str, None] = '68a3c7b85df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('content_hash', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_feedbacks_content_hash'), 'feedbacks', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_content_hash'), table_name='feedbacks')
    op.drop_column('feedbacks', 'content_hash')
    # ### end Alembic commands ###