"""add stripe fields to organizations

Revision ID: 68a3c7b85df0
Revises: 75298e98bd49
Create Date: 2026-06-28 17:38:31.146118

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '68a3c7b85df0'
down_revision: Union[str, None] = '75298e98bd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'stripe_subscription_id')
    op.drop_column('organizations', 'stripe_customer_id')
    # ### end Alembic commands ###