"""add clerk_user_id to users

Revision ID: 75298e98bd49
Revises: 981746acabee
Create Date: 2026-06-26 13:51:02.884310

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '75298e98bd49'
down_revision: Union[str, None] = '981746acabee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_user_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['clerk_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'clerk_user_id')
    # ### end Alembic commands ###