"""add clerk_org_id to organizations

Revision ID: 981746acabee
Revises: 4fb4cc1772bb
Create Date: 2026-06-26 12:45:24.163386

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '981746acabee'
down_revision: Union[str, None] = '4fb4cc1772bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('clerk_org_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'organizations', ['clerk_org_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'clerk_org_id')
    # ### end Alembic commands ###